//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reflector.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artifact
    {
        public long Id { get; set; }
        public int ArtifactHeaderId { get; set; }
        public string Classification { get; set; }
        public string Label { get; set; }
        public string Fact { get; set; }
        public System.DateTimeOffset DateTimeLogged { get; set; }
    
        public virtual ArtifactHeader ArtifactHeader { get; set; }
    }
}
